version: '3.8'

services:
  web:
    build: ./web-service
    container_name: 2022BCD0012_web
    ports:
      - "8080:8081"
    depends_on:
      - db
      - redis

  worker:
    build: ./worker-service
    container_name: 2022BCD0012_worker
    depends_on:
      - redis

  db:
    image: postgres
    container_name: 2022BCD0012_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservices_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: 2022BCD0012_redis
    restart: always

volumes:
  pgdata:
